# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x07\x61uth.v1\":\n\x0fValidateRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63\x61ller_host\x18\x02 \x01(\t\"x\n\x10ValidateResponse\x12\x35\n\x06\x66ields\x18\x01 \x03(\x0b\x32%.auth.v1.ValidateResponse.FieldsEntry\x1a-\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\";\n\x10ListUsersRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63\x61ller_host\x18\x02 \x01(\t\"h\n\x08ListUser\x12-\n\x06\x66ields\x18\x01 \x03(\x0b\x32\x1d.auth.v1.ListUser.FieldsEntry\x1a-\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"5\n\x11ListUsersResponse\x12 \n\x05users\x18\x01 \x03(\x0b\x32\x11.auth.v1.ListUser2\x8b\x01\n\x04\x41uth\x12?\n\x08Validate\x12\x18.auth.v1.ValidateRequest\x1a\x19.auth.v1.ValidateResponse\x12\x42\n\tListUsers\x12\x19.auth.v1.ListUsersRequest\x1a\x1a.auth.v1.ListUsersResponseB-Z+github.com/aleshka5/auth-service/pkg/authpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/aleshka5/auth-service/pkg/authpb'
  _globals['_VALIDATERESPONSE_FIELDSENTRY']._loaded_options = None
  _globals['_VALIDATERESPONSE_FIELDSENTRY']._serialized_options = b'8\001'
  _globals['_LISTUSER_FIELDSENTRY']._loaded_options = None
  _globals['_LISTUSER_FIELDSENTRY']._serialized_options = b'8\001'
  _globals['_VALIDATEREQUEST']._serialized_start=23
  _globals['_VALIDATEREQUEST']._serialized_end=81
  _globals['_VALIDATERESPONSE']._serialized_start=83
  _globals['_VALIDATERESPONSE']._serialized_end=203
  _globals['_VALIDATERESPONSE_FIELDSENTRY']._serialized_start=158
  _globals['_VALIDATERESPONSE_FIELDSENTRY']._serialized_end=203
  _globals['_LISTUSERSREQUEST']._serialized_start=205
  _globals['_LISTUSERSREQUEST']._serialized_end=264
  _globals['_LISTUSER']._serialized_start=266
  _globals['_LISTUSER']._serialized_end=370
  _globals['_LISTUSER_FIELDSENTRY']._serialized_start=158
  _globals['_LISTUSER_FIELDSENTRY']._serialized_end=203
  _globals['_LISTUSERSRESPONSE']._serialized_start=372
  _globals['_LISTUSERSRESPONSE']._serialized_end=425
  _globals['_AUTH']._serialized_start=428
  _globals['_AUTH']._serialized_end=567
# @@protoc_insertion_point(module_scope)
