from enum import StrEnum


class ErrorCode(StrEnum):
    QUOTA_EXCEEDED = "QUOTA_EXCEEDED"
    UNSUPPORTED_FORMAT = "UNSUPPORTED_FORMAT"
    PRIVATE_SESSION_EXPIRED = "PRIVATE_SESSION_EXPIRED"
    DISK_UNAVAILABLE = "DISK_UNAVAILABLE"
    PATH_TRAVERSAL_DETECTED = "PATH_TRAVERSAL_DETECTED"
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    ACCESS_DENIED = "ACCESS_DENIED"
