from enum import StrEnum


class ErrorCode(StrEnum):
    QUOTA_EXCEEDED = "QUOTA_EXCEEDED"
    UNSUPPORTED_FORMAT = "UNSUPPORTED_FORMAT"
    PRIVATE_SESSION_EXPIRED = "PRIVATE_SESSION_EXPIRED"
    DISK_UNAVAILABLE = "DISK_UNAVAILABLE"
    PATH_TRAVERSAL_DETECTED = "PATH_TRAVERSAL_DETECTED"
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    ACCESS_DENIED = "ACCESS_DENIED"
    TOO_MANY_ATTEMPTS = "TOO_MANY_ATTEMPTS"
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    UNAUTHORIZED = "UNAUTHORIZED"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    INTERNAL_ERROR = "INTERNAL_ERROR"
